Added two buttons and messagebox.
vsite-nwp-2015/v01 pull request #10
Opened 2016-10-03 22:07 UTC by Genato

2016-10-04 08:22 UTC, ncaklovic requested changes
Sve radi, samo par sitnica:
- CreateSolidBrush vraća HBRUSH, više ne treba cast (ni TODO komentar :-) )
- MB_DEFBUTTON1 ne treba kad je samo jedan button (MB_OK bi bolje objasnilo što će se pokazati)
  Može li se kod u OnCommand izvesti sa jednim pozivom MessageBox funkcije (DRY)?

2016-10-04 09:11 UTC, Genato commented
Izmjene radim ovdje ili u VS pa ponovo pull request?

2016-10-04 10:07 UTC, ncaklovic commented
Uvijek lokalno novi commit(ovi), ponovno "Push", nakon toga bi GitHub trebao prepoznati da nove commitove dodajete u postojeći Pull Request (probajte).

2016-10-04 21:45 UTC, Genato commented
Dali je dozvoljena konverzija tipva u neki drugi tip? npr. int to LPCSTR

2016-10-05 08:05 UTC, ncaklovic commented
- int u string: [std::to_string](http://en.cppreference.com/w/cpp/string/basic_string/to_string)
- za dobiti const char* poslije (PCSTR): član [c_str()](http://en.cppreference.com/w/cpp/string/basic_string/c_str) (to smo već koristili na OOP)

2016-10-05 13:07 UTC, Genato commented
Prvi pull request "Varijacije messagebox-a" mi nije povukao sve promjene pa sam napravio update "Update main.cpp", gdje su vidljive prave promjene.
Ovo sa std::to_string() sam direktno stavio u poziv funkcije ali onda ispisuje broj a ne string "one||two", a zakomentiranu verziju sam stavio da vidim dali je uredu i tako razmišljati.(Downside toga jel radi samo u slučaju true/false znači za dva slučaja..)

2016-10-05 14:20 UTC, ncaklovic commented
Rješenje koje bi podržavalo više opcija, a imalo samo jedan poziv API funkcije bi uključivalo višestruke if/else ili naravno switch, nešto poput:

```
	std::string txt, caption("NWP");
	switch (id) {
		case id_button1: txt = "one"; break;
		case id_button2: txt = "two"; break;
		default: return;
	}
	MessageBox(hw, txt.c_str(), caption.c_str(), MB_OK | MB_ICONWARNING);
```

2016-10-05 14:20 UTC, closed without merging